version: '3'

services:
  backend:
    container_name: backend_container
    build:
      context: ./backend/app
      dockerfile: Dockerfile.multi-stage
    env_file:
      - ./backend/app/.env
    restart: on-failure
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  postgres:
    container_name: postgresdb_container
    build:
      context: ./backend/db
      dockerfile: Dockerfile
    env_file:
      - ./backend/db/.env
    restart: on-failure
    ports:
      - "5433:5432"
    volumes:
      - postgresdb-data:/var/lib/postgresql/data

volumes:
  postgresdb-data:
